image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up --build -d
  - sleep 19
  - java -jar aqa-shop.jar -P:jdbc.url=jdbc:mysql://localhost:3306/database -P:jdbc.user=user -P:jdbc.password=password
  - sleep 19

build_script:
  - chmod +x gradlew
  - ./gradlew clean test -Dselenide.headless=true